liblzma: Fix HAVE_INLINE and HAVE___INLINE checks
The checks fail even on compilers that support the keywords because
the linkage is broken:

    src.c:...: undefined reference to 'test'

At the actual use sites we use `static inline` instead of just `inline`,
so perform the check this way too to fix the linkage.