KWIML: Add -Wno-format-security to tolerate -Werror=format-security
When compiling KWIML tests with `-Werror=format-security` we get

    error: -Wformat-security ignored without -Wformat

Therefore we should disable both `format` and `format-security`
together.