cmCTestSVN: Rename 'SVNInfo' members to 'SVNRepo'
Without this some compilers complain with errors such as:

 Source/CTest/cmCTestSVN.cxx:60: error: declaration of 'cmCTestSVN::SVNInfo& cmCTestSVN::InfoParser::SVNInfo'
 Source/CTest/cmCTestSVN.h:37: error: changes meaning of 'SVNInfo' from 'struct cmCTestSVN::SVNInfo'

because the member 'SVNInfo' of the nested InfoParser and LogParser
structs hides the cmCTestSVN::SVNInfo type name.