Tests/RunCMake/LinkStatic: Update for Xcode 26.4
`libtool` with Xcode 26.4 no longer fails on a missing object file:

    $ libtool -static -o libfoo.a foo.o missing.o ; echo exit-code=$?
    libtool: warning: file not found 'missing.o'
    exit-code=0

as it did with Xcode 26.3 and below:

    $ libtool -static -o libfoo.a foo.o missing.o ; echo exit-code=$?
    error: libtool: can't open file: missing.o (No such file or directory)
    exit-code=1

Use a bad flag instead.