Source: Restore compilation on FreeBSD
Since commit bda67b82e7 (instrumentation: Write cmakeBuild snippet when
build is interrupted, 2026-06-15) compilation on FreeBSD fails with:

    error: use of undeclared identifier 'isascii'

Follow our pattern from `cmTimestamp.cxx` to make `isascii` available.